//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proj.Loc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proj.Loc.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bardzo fajny program.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kup.
        /// </summary>
        public static string GridBuy {
            get {
                return ResourceManager.GetString("GridBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        public static string GridCategory {
            get {
                return ResourceManager.GetString("GridCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. ilość.
        /// </summary>
        public static string GridMaxQty {
            get {
                return ResourceManager.GetString("GridMaxQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. ilość.
        /// </summary>
        public static string GridMinQty {
            get {
                return ResourceManager.GetString("GridMinQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string GridProductId {
            get {
                return ResourceManager.GetString("GridProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string GridProductName {
            get {
                return ResourceManager.GetString("GridProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena zakupu.
        /// </summary>
        public static string GridPurchasePrice {
            get {
                return ResourceManager.GetString("GridPurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość.
        /// </summary>
        public static string GridQty {
            get {
                return ResourceManager.GetString("GridQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena sprzedaży.
        /// </summary>
        public static string GridSalePrice {
            get {
                return ResourceManager.GetString("GridSalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka sprzedaży.
        /// </summary>
        public static string GridSaleUnit {
            get {
                return ResourceManager.GetString("GridSaleUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dodaj linię.
        /// </summary>
        public static string MenuAddLine {
            get {
                return ResourceManager.GetString("MenuAddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Według _zaznaczenia &quot;Kup&quot;.
        /// </summary>
        public static string MenuByBuySelection {
            get {
                return ResourceManager.GetString("MenuByBuySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Według _kategorii rosnąco.
        /// </summary>
        public static string MenuByCategoryAsc {
            get {
                return ResourceManager.GetString("MenuByCategoryAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Według kategorii malejąco.
        /// </summary>
        public static string MenuByCategoryDesc {
            get {
                return ResourceManager.GetString("MenuByCategoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Według _nazwy rosnąco.
        /// </summary>
        public static string MenuByNameAsc {
            get {
                return ResourceManager.GetString("MenuByNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Według nazwy malejąco.
        /// </summary>
        public static string MenuByNameDesc {
            get {
                return ResourceManager.GetString("MenuByNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Według ceny _zakupu rosnąco.
        /// </summary>
        public static string MenuByPurchasePriceAsc {
            get {
                return ResourceManager.GetString("MenuByPurchasePriceAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Według ceny zakupu malejąco.
        /// </summary>
        public static string MenuByPurchasePriceDesc {
            get {
                return ResourceManager.GetString("MenuByPurchasePriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Według _ilości rosnąco.
        /// </summary>
        public static string MenuByQuantityAsc {
            get {
                return ResourceManager.GetString("MenuByQuantityAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Według ilości malejąco.
        /// </summary>
        public static string MenuByQuantityDesc {
            get {
                return ResourceManager.GetString("MenuByQuantityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Według ceny _sprzedaży rosnąco.
        /// </summary>
        public static string MenuBySellPriceAsc {
            get {
                return ResourceManager.GetString("MenuBySellPriceAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Według ceny sprzedaży malejąco.
        /// </summary>
        public static string MenuBySellPriceDesc {
            get {
                return ResourceManager.GetString("MenuBySellPriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Generuj.
        /// </summary>
        public static string MenuCreate {
            get {
                return ResourceManager.GetString("MenuCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj listę _sprzedaży....
        /// </summary>
        public static string MenuCreateSalesList {
            get {
                return ResourceManager.GetString("MenuCreateSalesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj listę _zakupów....
        /// </summary>
        public static string MenuCreateShoppingList {
            get {
                return ResourceManager.GetString("MenuCreateShoppingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Wyjście.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Plik.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Pomoc.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Informacje.
        /// </summary>
        public static string MenuInformation {
            get {
                return ResourceManager.GetString("MenuInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Lista.
        /// </summary>
        public static string MenuList {
            get {
                return ResourceManager.GetString("MenuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Nowy plik....
        /// </summary>
        public static string MenuNewFile {
            get {
                return ResourceManager.GetString("MenuNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Otwórz plik....
        /// </summary>
        public static string MenuOpenFile {
            get {
                return ResourceManager.GetString("MenuOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odwrotnie do zaznaczenia &quot;Kup&quot;.
        /// </summary>
        public static string MenuOppToBuySelection {
            get {
                return ResourceManager.GetString("MenuOppToBuySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Usuń linię.
        /// </summary>
        public static string MenuRemoveLine {
            get {
                return ResourceManager.GetString("MenuRemoveLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapi_sz plik jako....
        /// </summary>
        public static string MenuSaveAsFile {
            get {
                return ResourceManager.GetString("MenuSaveAsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Zapisz plik.
        /// </summary>
        public static string MenuSaveFile {
            get {
                return ResourceManager.GetString("MenuSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sortuj.
        /// </summary>
        public static string MenuSort {
            get {
                return ResourceManager.GetString("MenuSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość produktów do kupienia:.
        /// </summary>
        public static string StatusbarBuyNumber {
            get {
                return ResourceManager.GetString("StatusbarBuyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przychód ze sprzedaży:.
        /// </summary>
        public static string StatusbarIncome {
            get {
                return ResourceManager.GetString("StatusbarIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koszt zakupu:.
        /// </summary>
        public static string StatusbarPurchaseCost {
            get {
                return ResourceManager.GetString("StatusbarPurchaseCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość wszystkich produktów:.
        /// </summary>
        public static string StatusbarTotalNumber {
            get {
                return ResourceManager.GetString("StatusbarTotalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj linię.
        /// </summary>
        public static string ToolbarBtnAddLine {
            get {
                return ResourceManager.GetString("ToolbarBtnAddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj listę sprzedaży.
        /// </summary>
        public static string ToolbarBtnCreateSalesList {
            get {
                return ResourceManager.GetString("ToolbarBtnCreateSalesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj listę zakupów.
        /// </summary>
        public static string ToolbarBtnCreateShoppingList {
            get {
                return ResourceManager.GetString("ToolbarBtnCreateShoppingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesuń w dół.
        /// </summary>
        public static string ToolbarBtnMoveDown {
            get {
                return ResourceManager.GetString("ToolbarBtnMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesuń w górę.
        /// </summary>
        public static string ToolbarBtnMoveUp {
            get {
                return ResourceManager.GetString("ToolbarBtnMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy plik.
        /// </summary>
        public static string ToolbarBtnNewFile {
            get {
                return ResourceManager.GetString("ToolbarBtnNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz plik.
        /// </summary>
        public static string ToolbarBtnOpenFile {
            get {
                return ResourceManager.GetString("ToolbarBtnOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń linię.
        /// </summary>
        public static string ToolbarBtnRemoveLine {
            get {
                return ResourceManager.GetString("ToolbarBtnRemoveLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz plik.
        /// </summary>
        public static string ToolbarBtnSaveFile {
            get {
                return ResourceManager.GetString("ToolbarBtnSaveFile", resourceCulture);
            }
        }
    }
}
